
.PHONY: build
build:
	@truffle compile

.PHONY: start/testrpc
start/testrpc:
	@ganache-cli -m "benefit come fiscal degree photo you abstract casino heart habit early pact"

.PHONY: deploy
deploy:
	@truffle deploy

.PHONY: test
test:
	@truffle test
